# Generated by Django 5.2.3 on 2025-11-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='세션 키 또는 사용자 식별자', max_length=255, unique=True)),
                ('region', models.CharField(blank=True, choices=[('seoul-guanak', '서울특별시 관악구'), ('seoul-geumcheon', '서울특별시 금천구'), ('seoul-dongjak', '서울특별시 동작구')], max_length=50, null=True)),
                ('enabled', models.BooleanField(default=True, help_text='알림 활성화 여부')),
                ('notify_before', models.BooleanField(default=True, help_text='수거 전날 알림')),
                ('notify_day', models.BooleanField(default=True, help_text='수거 당일 알림')),
                ('notification_time', models.TimeField(default='20:00', help_text='알림 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정',
            },
        ),
    ]
