# Generated by Django 5.2.3 on 2025-11-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='지역 코드 (예: seoul-guanak)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='지역 이름 (예: 서울특별시 관악구)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
            },
        ),
        migrations.CreateModel(
            name='RegionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_time', models.CharField(help_text='배출 시간 (예: 18:00 ~ 24:00)', max_length=200)),
                ('residential_area_time', models.CharField(blank=True, help_text='주거지역 배출 시간', max_length=200, null=True)),
                ('commercial_area_time', models.CharField(blank=True, help_text='상가지역/가로지역 배출 시간', max_length=200, null=True)),
                ('discharge_location', models.CharField(help_text='배출 장소', max_length=200)),
                ('discharge_method', models.CharField(help_text='배출 방법', max_length=200)),
                ('special_note', models.TextField(blank=True, help_text='특별 배출 사항', null=True)),
                ('contact', models.CharField(help_text='문의처', max_length=100)),
                ('collection_days', models.JSONField(default=list, help_text='수거 요일 (0=일요일, 1=월요일, ...)')),
                ('waste_pattern', models.JSONField(default=list, help_text='쓰레기 종류 패턴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(help_text='지역', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pages.region')),
            ],
            options={
                'verbose_name': '지역별 수거 일정',
                'verbose_name_plural': '지역별 수거 일정',
                'unique_together': {('region',)},
            },
        ),
    ]
